spring:
  profiles:
    active: default,local

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  application:
    name: cgmes-boundary-server

server:
  forward-headers-strategy: framework
