name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-generic.yml@baf0d2ed84b70d359132693880d5e530cd93f168
    with:
      sonarOrganization: gridsuite
      sonarProjectKey: org.gridsuite:cgmes-boundary-server
      dockerImage: docker.io/gridsuite/cgmes-boundary-server
      dockerUsername: gridsuiteci
      eventType: cgmes_boundary_server_updated
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
